version: '2'
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: node
    volumes:
      - ../:/usr/app
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    #restart: always
